package workflow_test

import (
	"errors"
	"log/slog"
	"testing"

	"github.com/Pleasurecruise/eyeful/workflow"
)

const patch = `diff --git a/app/session.py b/app/session.py
index 1111111..2222222 100644
--- a/app/session.py
+++ b/app/session.py
@@ -1,3 +1,3 @@
 def is_expired(session, now):
-    return now > session.expires_at
+    return now >= session.expires_at
+--- not a header
diff --git a/old name.go b/new name.go
similarity 90%
rename from old name.go
rename to new name.go
diff --git a/gone.txt b/gone.txt
deleted file mode 100644
index 3333333..0000000
--- a/gone.txt
+++ /dev/null
@@ -1,2 +0,0 @@
-a
-b
diff --git a/logo.png b/logo.png
new file mode 100644
index 0000000..4444444
Binary files /dev/null and b/logo.png differ
diff --git "a/caf\303\251.md" "b/caf\303\251.md"
new file mode 100644
--- /dev/null
+++ "b/caf\303\251.md"
@@ -0,0 +1 @@
+hello
`

func TestSplitPatch(t *testing.T) {
	files, err := workflow.SplitPatch(patch)
	if err != nil {
		t.Fatal(err)
	}
	want := []workflow.File{
		{Path: "app/session.py", Added: 2, Deleted: 1},
		{Path: "new name.go"},
		{Path: "gone.txt", Deleted: 2},
		{Path: "logo.png", Binary: true},
		{Path: "café.md", Added: 1},
	}
	if len(files) != len(want) {
		t.Fatalf("got %d files", len(files))
	}
	for i, w := range want {
		f := files[i]
		if f.Path != w.Path || f.Added != w.Added || f.Deleted != w.Deleted || f.Binary != w.Binary || f.Diff == "" {
			t.Errorf("file %d: got %+v, want %+v", i, f, w)
		}
	}

	if files, err := workflow.SplitPatch(""); err != nil || len(files) != 0 {
		t.Errorf("empty patch: %v, %v", files, err)
	}
	if _, err := workflow.SplitPatch("hello\n"); !errors.Is(err, workflow.ErrInvalidPatch) {
		t.Errorf("garbage: %v", err)
	}
}

func TestTriage(t *testing.T) {
	a := base()
	var manifest []workflow.Entry
	a.plan = func(t workflow.PlanTask) (workflow.Plan, error) {
		manifest = t.Manifest
		return goodPlan(t)
	}
	req := request()
	req.Project = workflow.Project{Skip: []string{"docs/api/**"}, Risk: []string{"app/auth/**"}}
	req.Change.Files = []workflow.File{
		{Path: "app/session.py"},
		{Path: "app/login.py"},
		{Path: "app/test_session.py"},
		{Path: "README.md"},
		{Path: "web/pnpm-lock.yaml"},
		{Path: "vendor/x/y.go"},
		{Path: "api/types.pb.go"},
		{Path: "api/client.go", Diff: "+// Code generated by oapi-codegen. DO NOT EDIT.\n"},
		{Path: "logo.png", Binary: true},
		{Path: "docs/api/index.md"},
	}
	res := run(t, a, &workspace{ci: workflow.Check{Passed: true}}, &archive{}, req)
	want := map[string]workflow.Class{
		"app/session.py": workflow.ClassCode, "app/login.py": workflow.ClassCode, "app/test_session.py": workflow.ClassTest,
		"README.md": workflow.ClassDocs, "web/pnpm-lock.yaml": workflow.ClassLock, "vendor/x/y.go": workflow.ClassVendored,
		"api/types.pb.go": workflow.ClassGenerated, "api/client.go": workflow.ClassGenerated, "logo.png": workflow.ClassBinary,
		"docs/api/index.md": workflow.ClassSkipped,
	}
	if len(manifest) != len(want) || len(res.Triage.Reviewed) != 4 || len(res.Triage.Excluded) != 6 {
		t.Fatalf("manifest %+v", manifest)
	}
	for _, e := range manifest {
		if want[e.Path] != e.Class {
			t.Errorf("%s: got %s, want %s", e.Path, e.Class, want[e.Path])
		}
	}
	if res.PlanSource != workflow.PlanFromDefault {
		t.Errorf("a plan missing test_session.py and README.md was accepted")
	}

	req.Level = ""
	req.Change.Files = append(req.Change.Files, workflow.File{Path: "app/auth/token.py"})
	if res := run(t, base(), &workspace{ci: workflow.Check{Passed: true}}, &archive{}, req); res.Level != workflow.LevelDeep || len(res.Triage.Risk) != 1 {
		t.Errorf("risk path: level %s, risk %v", res.Level, res.Triage.Risk)
	}
	req.Change.Files = []workflow.File{{Path: "app/session.py", Added: 3}}
	if res := run(t, base(), &workspace{ci: workflow.Check{Passed: true}}, &archive{}, req); res.Level != workflow.LevelStandard {
		t.Errorf("small change: level %s", res.Level)
	}

	req.Project.Risk = []string{"app/[x"}
	w, err := workflow.New(slog.New(slog.DiscardHandler), roster)
	if err == nil {
		_, err = w.Run(t.Context(), workflow.Session{}, req)
	}
	if !errors.Is(err, workflow.ErrInvalidRequest) {
		t.Errorf("bad glob: %v", err)
	}
}
