// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AuthorizeOAuthData, AuthorizeOAuthErrors, CallbackOAuthData, CallbackOAuthErrors, CreateApiKeyData, CreateApiKeyErrors, CreateApiKeyResponses, CreateReviewData, CreateReviewErrors, CreateReviewResponses, DeleteApiKeyData, DeleteApiKeyErrors, DeleteApiKeyResponses, DeleteCurrentSessionData, DeleteCurrentSessionErrors, DeleteCurrentSessionResponses, DeleteCurrentUserData, DeleteCurrentUserErrors, DeleteCurrentUserResponses, DeleteReviewData, DeleteReviewErrors, DeleteReviewResponses, DeleteSessionData, DeleteSessionErrors, DeleteSessionResponses, GetApiKeyData, GetApiKeyErrors, GetApiKeyResponses, GetCurrentSessionData, GetCurrentSessionErrors, GetCurrentSessionResponses, GetCurrentUserData, GetCurrentUserErrors, GetCurrentUserResponses, GetHealthData, GetHealthResponses, GetReadinessData, GetReadinessErrors, GetReadinessResponses, GetRepositoryCommitData, GetRepositoryCommitDiffData, GetRepositoryCommitDiffErrors, GetRepositoryCommitDiffResponses, GetRepositoryCommitErrors, GetRepositoryCommitResponses, GetRepositoryData, GetRepositoryErrors, GetRepositoryResponses, GetRepositoryTreeData, GetRepositoryTreeErrors, GetRepositoryTreeResponses, GetReviewData, GetReviewErrors, GetReviewResponses, ListApiKeysData, ListApiKeysErrors, ListApiKeysResponses, ListOAuthProvidersData, ListOAuthProvidersErrors, ListOAuthProvidersResponses, ListRepositoriesData, ListRepositoriesErrors, ListRepositoriesResponses, ListReviewsData, ListReviewsErrors, ListReviewsResponses, ListSessionsData, ListSessionsErrors, ListSessionsResponses, UpdateApiKeyData, UpdateApiKeyErrors, UpdateApiKeyResponses, UpdateCurrentUserData, UpdateCurrentUserErrors, UpdateCurrentUserResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List API keys
 */
export const listApiKeys = <ThrowOnError extends boolean = false>(options?: Options<ListApiKeysData, ThrowOnError>): RequestResult<ListApiKeysResponses, ListApiKeysErrors, ThrowOnError> => (options?.client ?? client).get<ListApiKeysResponses, ListApiKeysErrors, ThrowOnError>({ url: '/api-keys', ...options });

/**
 * Create an API key
 *
 * The secret is returned only here; store it now.
 */
export const createApiKey = <ThrowOnError extends boolean = false>(options: Options<CreateApiKeyData, ThrowOnError>): RequestResult<CreateApiKeyResponses, CreateApiKeyErrors, ThrowOnError> => (options.client ?? client).post<CreateApiKeyResponses, CreateApiKeyErrors, ThrowOnError>({
    url: '/api-keys',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Revoke an API key
 */
export const deleteApiKey = <ThrowOnError extends boolean = false>(options: Options<DeleteApiKeyData, ThrowOnError>): RequestResult<DeleteApiKeyResponses, DeleteApiKeyErrors, ThrowOnError> => (options.client ?? client).delete<DeleteApiKeyResponses, DeleteApiKeyErrors, ThrowOnError>({ url: '/api-keys/{id}', ...options });

/**
 * Get one API key
 */
export const getApiKey = <ThrowOnError extends boolean = false>(options: Options<GetApiKeyData, ThrowOnError>): RequestResult<GetApiKeyResponses, GetApiKeyErrors, ThrowOnError> => (options.client ?? client).get<GetApiKeyResponses, GetApiKeyErrors, ThrowOnError>({ url: '/api-keys/{id}', ...options });

/**
 * Rename an API key
 */
export const updateApiKey = <ThrowOnError extends boolean = false>(options: Options<UpdateApiKeyData, ThrowOnError>): RequestResult<UpdateApiKeyResponses, UpdateApiKeyErrors, ThrowOnError> => (options.client ?? client).patch<UpdateApiKeyResponses, UpdateApiKeyErrors, ThrowOnError>({
    url: '/api-keys/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Liveness
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>): RequestResult<GetHealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Sign-in providers this server is configured for
 */
export const listOAuthProviders = <ThrowOnError extends boolean = false>(options?: Options<ListOAuthProvidersData, ThrowOnError>): RequestResult<ListOAuthProvidersResponses, ListOAuthProvidersErrors, ThrowOnError> => (options?.client ?? client).get<ListOAuthProvidersResponses, ListOAuthProvidersErrors, ThrowOnError>({ url: '/oauth/providers', ...options });

/**
 * Redirect to the provider to sign in
 */
export const authorizeOAuth = <ThrowOnError extends boolean = false>(options: Options<AuthorizeOAuthData, ThrowOnError>): RequestResult<unknown, AuthorizeOAuthErrors, ThrowOnError> => (options.client ?? client).get<unknown, AuthorizeOAuthErrors, ThrowOnError>({ url: '/oauth/{provider}/authorize', ...options });

/**
 * The provider redirects here; sets the session and returns to the console
 */
export const callbackOAuth = <ThrowOnError extends boolean = false>(options: Options<CallbackOAuthData, ThrowOnError>): RequestResult<unknown, CallbackOAuthErrors, ThrowOnError> => (options.client ?? client).get<unknown, CallbackOAuthErrors, ThrowOnError>({ url: '/oauth/{provider}/callback', ...options });

/**
 * Readiness: the database answers
 */
export const getReadiness = <ThrowOnError extends boolean = false>(options?: Options<GetReadinessData, ThrowOnError>): RequestResult<GetReadinessResponses, GetReadinessErrors, ThrowOnError> => (options?.client ?? client).get<GetReadinessResponses, GetReadinessErrors, ThrowOnError>({ url: '/ready', ...options });

/**
 * The GitHub repositories the signed-in user gave eyeful
 *
 * Every installation of the GitHub App the user can access, with every repository of each. An installation's html_url is where the user changes its repositories.
 */
export const listRepositories = <ThrowOnError extends boolean = false>(options?: Options<ListRepositoriesData, ThrowOnError>): RequestResult<ListRepositoriesResponses, ListRepositoriesErrors, ThrowOnError> => (options?.client ?? client).get<ListRepositoriesResponses, ListRepositoriesErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'eyeful_session',
            type: 'apiKey'
        }],
    url: '/repositories',
    ...options
});

/**
 * A GitHub repository the signed-in user gave eyeful
 *
 * The fields of GitHub's full-repository schema the console needs, read with the user's GitHub App token.
 */
export const getRepository = <ThrowOnError extends boolean = false>(options: Options<GetRepositoryData, ThrowOnError>): RequestResult<GetRepositoryResponses, GetRepositoryErrors, ThrowOnError> => (options.client ?? client).get<GetRepositoryResponses, GetRepositoryErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'eyeful_session',
            type: 'apiKey'
        }],
    url: '/repositories/{owner}/{name}',
    ...options
});

/**
 * A commit, by sha or branch
 *
 * The fields of GitHub's commit schema the console needs, without its files.
 */
export const getRepositoryCommit = <ThrowOnError extends boolean = false>(options: Options<GetRepositoryCommitData, ThrowOnError>): RequestResult<GetRepositoryCommitResponses, GetRepositoryCommitErrors, ThrowOnError> => (options.client ?? client).get<GetRepositoryCommitResponses, GetRepositoryCommitErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'eyeful_session',
            type: 'apiKey'
        }],
    url: '/repositories/{owner}/{name}/commits/{ref}',
    ...options
});

/**
 * The unified diff a commit made against its first parent
 */
export const getRepositoryCommitDiff = <ThrowOnError extends boolean = false>(options: Options<GetRepositoryCommitDiffData, ThrowOnError>): RequestResult<GetRepositoryCommitDiffResponses, GetRepositoryCommitDiffErrors, ThrowOnError> => (options.client ?? client).get<GetRepositoryCommitDiffResponses, GetRepositoryCommitDiffErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'eyeful_session',
            type: 'apiKey'
        }],
    url: '/repositories/{owner}/{name}/commits/{ref}/diff',
    ...options
});

/**
 * A git tree, recursively
 *
 * GitHub's git-tree schema. truncated is true when GitHub returned only part of a large tree.
 */
export const getRepositoryTree = <ThrowOnError extends boolean = false>(options: Options<GetRepositoryTreeData, ThrowOnError>): RequestResult<GetRepositoryTreeResponses, GetRepositoryTreeErrors, ThrowOnError> => (options.client ?? client).get<GetRepositoryTreeResponses, GetRepositoryTreeErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'eyeful_session',
            type: 'apiKey'
        }],
    url: '/repositories/{owner}/{name}/git/trees/{sha}',
    ...options
});

/**
 * List reviews, newest first
 */
export const listReviews = <ThrowOnError extends boolean = false>(options?: Options<ListReviewsData, ThrowOnError>): RequestResult<ListReviewsResponses, ListReviewsErrors, ThrowOnError> => (options?.client ?? client).get<ListReviewsResponses, ListReviewsErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'eyeful_session',
            type: 'apiKey'
        }],
    url: '/reviews',
    ...options
});

/**
 * Queue a review
 *
 * Returns 202 with the queued review. A review cannot be stopped once it runs, so clients confirm before creating one. Repeating a request with the same Idempotency-Key returns the first review; reusing the key with a different body is a 409.
 */
export const createReview = <ThrowOnError extends boolean = false>(options: Options<CreateReviewData, ThrowOnError>): RequestResult<CreateReviewResponses, CreateReviewErrors, ThrowOnError> => (options.client ?? client).post<CreateReviewResponses, CreateReviewErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'eyeful_session',
            type: 'apiKey'
        }],
    url: '/reviews',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a queued or done review
 */
export const deleteReview = <ThrowOnError extends boolean = false>(options: Options<DeleteReviewData, ThrowOnError>): RequestResult<DeleteReviewResponses, DeleteReviewErrors, ThrowOnError> => (options.client ?? client).delete<DeleteReviewResponses, DeleteReviewErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'eyeful_session',
            type: 'apiKey'
        }],
    url: '/reviews/{id}',
    ...options
});

/**
 * Get one review
 */
export const getReview = <ThrowOnError extends boolean = false>(options: Options<GetReviewData, ThrowOnError>): RequestResult<GetReviewResponses, GetReviewErrors, ThrowOnError> => (options.client ?? client).get<GetReviewResponses, GetReviewErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'eyeful_session',
            type: 'apiKey'
        }],
    url: '/reviews/{id}',
    ...options
});

/**
 * List the signed-in user's active sessions
 */
export const listSessions = <ThrowOnError extends boolean = false>(options?: Options<ListSessionsData, ThrowOnError>): RequestResult<ListSessionsResponses, ListSessionsErrors, ThrowOnError> => (options?.client ?? client).get<ListSessionsResponses, ListSessionsErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'eyeful_session',
            type: 'apiKey'
        }],
    url: '/sessions',
    ...options
});

/**
 * Sign out of this browser
 */
export const deleteCurrentSession = <ThrowOnError extends boolean = false>(options?: Options<DeleteCurrentSessionData, ThrowOnError>): RequestResult<DeleteCurrentSessionResponses, DeleteCurrentSessionErrors, ThrowOnError> => (options?.client ?? client).delete<DeleteCurrentSessionResponses, DeleteCurrentSessionErrors, ThrowOnError>({ url: '/sessions/current', ...options });

/**
 * Who is calling, and how
 */
export const getCurrentSession = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentSessionData, ThrowOnError>): RequestResult<GetCurrentSessionResponses, GetCurrentSessionErrors, ThrowOnError> => (options?.client ?? client).get<GetCurrentSessionResponses, GetCurrentSessionErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'eyeful_session',
            type: 'apiKey'
        }],
    url: '/sessions/current',
    ...options
});

/**
 * Sign out another device
 */
export const deleteSession = <ThrowOnError extends boolean = false>(options: Options<DeleteSessionData, ThrowOnError>): RequestResult<DeleteSessionResponses, DeleteSessionErrors, ThrowOnError> => (options.client ?? client).delete<DeleteSessionResponses, DeleteSessionErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'eyeful_session',
            type: 'apiKey'
        }],
    url: '/sessions/{id}',
    ...options
});

/**
 * Delete the signed-in user with their sessions, keys and reviews
 */
export const deleteCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<DeleteCurrentUserData, ThrowOnError>): RequestResult<DeleteCurrentUserResponses, DeleteCurrentUserErrors, ThrowOnError> => (options?.client ?? client).delete<DeleteCurrentUserResponses, DeleteCurrentUserErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'eyeful_session',
            type: 'apiKey'
        }],
    url: '/users/me',
    ...options
});

/**
 * The signed-in user
 */
export const getCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentUserData, ThrowOnError>): RequestResult<GetCurrentUserResponses, GetCurrentUserErrors, ThrowOnError> => (options?.client ?? client).get<GetCurrentUserResponses, GetCurrentUserErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'eyeful_session',
            type: 'apiKey'
        }],
    url: '/users/me',
    ...options
});

/**
 * Change the signed-in user's name
 */
export const updateCurrentUser = <ThrowOnError extends boolean = false>(options: Options<UpdateCurrentUserData, ThrowOnError>): RequestResult<UpdateCurrentUserResponses, UpdateCurrentUserErrors, ThrowOnError> => (options.client ?? client).patch<UpdateCurrentUserResponses, UpdateCurrentUserErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'eyeful_session',
            type: 'apiKey'
        }],
    url: '/users/me',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
