// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type ApiKey = {
    created_at: string;
    id: string;
    last_used_at?: string;
    name: string;
    prefix: string;
};

export type ApiKeyList = {
    items: Array<ApiKey>;
};

export type Commit = {
    commit: GitCommit;
    html_url: string;
    parents: Array<CommitParent>;
    sha: string;
};

export type CommitDiff = {
    diff: string;
};

export type CommitParent = {
    sha: string;
};

export type CreateApiKeyRequest = {
    name: string;
};

export type CreateReviewRequest = {
    note?: string;
    source: Source;
};

export type CreatedApiKey = {
    key: ApiKey;
    secret: string;
};

export type CurrentSession = {
    user: User;
    via: 'session' | 'api_key';
};

export type ErrorCode = 'bad_request' | 'unauthenticated' | 'not_found' | 'method_not_allowed' | 'internal' | 'unavailable' | 'review_not_found' | 'idempotency_conflict' | 'rate_limited' | 'invalid_credentials' | 'email_taken' | 'invalid_email' | 'weak_password' | 'api_key_not_found' | 'session_not_found' | 'review_running' | 'origin_forbidden' | 'repository_not_found' | 'provider_not_linked' | 'provider_expired';

export type GitCommit = {
    author?: GitUser;
    committer?: GitUser;
    message: string;
    tree: TreeRef;
};

export type GitTree = {
    sha: string;
    tree: Array<GitTreeEntry>;
    truncated: boolean;
};

export type GitTreeEntry = {
    mode: string;
    path: string;
    sha: string;
    size?: number;
    type: string;
};

export type GitUser = {
    date?: string;
    email?: string;
    name?: string;
};

export type HealthResponse = {
    status: string;
    version: string;
};

export type Installation = {
    account?: InstallationAccount;
    html_url: string;
    id: number;
    repository_selection: 'all' | 'selected';
    target_type: string;
};

export type InstallationAccount = {
    login: string;
};

export type OAuthProvider = {
    id: 'github' | 'gitee';
    title: string;
};

export type OAuthProviderList = {
    items: Array<OAuthProvider>;
};

export type Problem = {
    code: ErrorCode;
    detail?: string;
    request_id?: string;
    status: number;
    title: string;
    type: string;
};

export type Repository = {
    default_branch: string;
    full_name: string;
    html_url: string;
    name: string;
    owner: RepositoryOwner;
    private: boolean;
};

export type RepositoryList = {
    installations: Array<Installation>;
    items: Array<Repository>;
};

export type RepositoryOwner = {
    login: string;
};

export type Review = {
    attempts: number;
    created_at: string;
    finished_at?: string;
    id: string;
    note?: string;
    reason?: string;
    result?: 'complete' | 'none';
    source: Source;
    started_at?: string;
    status: 'queued' | 'running' | 'done';
};

export type ReviewList = {
    items: Array<Review>;
};

export type Session = {
    created_at: string;
    expires_at: string;
    id: string;
    ip?: string;
    user_agent?: string;
};

export type SessionList = {
    items: Array<Session>;
};

export type Source = {
    base: string;
    head: string;
    repo: string;
};

export type TreeRef = {
    sha: string;
};

export type UpdateApiKeyRequest = {
    name: string;
};

export type UpdateUserRequest = {
    name: string;
};

export type User = {
    created_at: string;
    email: string;
    id: string;
    name?: string;
};

export type ListApiKeysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api-keys';
};

export type ListApiKeysErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
};

export type ListApiKeysError = ListApiKeysErrors[keyof ListApiKeysErrors];

export type ListApiKeysResponses = {
    /**
     * OK
     */
    200: ApiKeyList;
};

export type ListApiKeysResponse = ListApiKeysResponses[keyof ListApiKeysResponses];

export type CreateApiKeyData = {
    /**
     * Key name
     */
    body: CreateApiKeyRequest;
    path?: never;
    query?: never;
    url: '/api-keys';
};

export type CreateApiKeyErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
};

export type CreateApiKeyError = CreateApiKeyErrors[keyof CreateApiKeyErrors];

export type CreateApiKeyResponses = {
    /**
     * Created
     */
    201: CreatedApiKey;
};

export type CreateApiKeyResponse = CreateApiKeyResponses[keyof CreateApiKeyResponses];

export type DeleteApiKeyData = {
    body?: never;
    path: {
        /**
         * Key ID
         */
        id: string;
    };
    query?: never;
    url: '/api-keys/{id}';
};

export type DeleteApiKeyErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
};

export type DeleteApiKeyError = DeleteApiKeyErrors[keyof DeleteApiKeyErrors];

export type DeleteApiKeyResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiKeyResponse = DeleteApiKeyResponses[keyof DeleteApiKeyResponses];

export type GetApiKeyData = {
    body?: never;
    path: {
        /**
         * Key ID
         */
        id: string;
    };
    query?: never;
    url: '/api-keys/{id}';
};

export type GetApiKeyErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
};

export type GetApiKeyError = GetApiKeyErrors[keyof GetApiKeyErrors];

export type GetApiKeyResponses = {
    /**
     * OK
     */
    200: ApiKey;
};

export type GetApiKeyResponse = GetApiKeyResponses[keyof GetApiKeyResponses];

export type UpdateApiKeyData = {
    /**
     * New name
     */
    body: UpdateApiKeyRequest;
    path: {
        /**
         * Key ID
         */
        id: string;
    };
    query?: never;
    url: '/api-keys/{id}';
};

export type UpdateApiKeyErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
};

export type UpdateApiKeyError = UpdateApiKeyErrors[keyof UpdateApiKeyErrors];

export type UpdateApiKeyResponses = {
    /**
     * OK
     */
    200: ApiKey;
};

export type UpdateApiKeyResponse = UpdateApiKeyResponses[keyof UpdateApiKeyResponses];

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * OK
     */
    200: HealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type ListOAuthProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/oauth/providers';
};

export type ListOAuthProvidersErrors = {
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type ListOAuthProvidersError = ListOAuthProvidersErrors[keyof ListOAuthProvidersErrors];

export type ListOAuthProvidersResponses = {
    /**
     * OK
     */
    200: OAuthProviderList;
};

export type ListOAuthProvidersResponse = ListOAuthProvidersResponses[keyof ListOAuthProvidersResponses];

export type AuthorizeOAuthData = {
    body?: never;
    path: {
        /**
         * Provider
         */
        provider: 'github' | 'gitee';
    };
    query?: never;
    url: '/oauth/{provider}/authorize';
};

export type AuthorizeOAuthErrors = {
    /**
     * Not Found
     */
    404: Problem;
};

export type AuthorizeOAuthError = AuthorizeOAuthErrors[keyof AuthorizeOAuthErrors];

export type CallbackOAuthData = {
    body?: never;
    path: {
        /**
         * Provider
         */
        provider: 'github' | 'gitee';
    };
    query: {
        /**
         * Authorization code
         */
        code: string;
        /**
         * State from the authorize redirect
         */
        state: string;
    };
    url: '/oauth/{provider}/callback';
};

export type CallbackOAuthErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not Found
     */
    404: Problem;
};

export type CallbackOAuthError = CallbackOAuthErrors[keyof CallbackOAuthErrors];

export type GetReadinessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ready';
};

export type GetReadinessErrors = {
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type GetReadinessError = GetReadinessErrors[keyof GetReadinessErrors];

export type GetReadinessResponses = {
    /**
     * OK
     */
    200: HealthResponse;
};

export type GetReadinessResponse = GetReadinessResponses[keyof GetReadinessResponses];

export type ListRepositoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/repositories';
};

export type ListRepositoriesErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type ListRepositoriesError = ListRepositoriesErrors[keyof ListRepositoriesErrors];

export type ListRepositoriesResponses = {
    /**
     * OK
     */
    200: RepositoryList;
};

export type ListRepositoriesResponse = ListRepositoriesResponses[keyof ListRepositoriesResponses];

export type GetRepositoryData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/repositories/{owner}/{name}';
};

export type GetRepositoryErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type GetRepositoryError = GetRepositoryErrors[keyof GetRepositoryErrors];

export type GetRepositoryResponses = {
    /**
     * OK
     */
    200: Repository;
};

export type GetRepositoryResponse = GetRepositoryResponses[keyof GetRepositoryResponses];

export type GetRepositoryCommitData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Name
         */
        name: string;
        /**
         * Commit sha or branch
         */
        ref: string;
    };
    query?: never;
    url: '/repositories/{owner}/{name}/commits/{ref}';
};

export type GetRepositoryCommitErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type GetRepositoryCommitError = GetRepositoryCommitErrors[keyof GetRepositoryCommitErrors];

export type GetRepositoryCommitResponses = {
    /**
     * OK
     */
    200: Commit;
};

export type GetRepositoryCommitResponse = GetRepositoryCommitResponses[keyof GetRepositoryCommitResponses];

export type GetRepositoryCommitDiffData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Name
         */
        name: string;
        /**
         * Full commit sha
         */
        ref: string;
    };
    query?: never;
    url: '/repositories/{owner}/{name}/commits/{ref}/diff';
};

export type GetRepositoryCommitDiffErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type GetRepositoryCommitDiffError = GetRepositoryCommitDiffErrors[keyof GetRepositoryCommitDiffErrors];

export type GetRepositoryCommitDiffResponses = {
    /**
     * OK
     */
    200: CommitDiff;
};

export type GetRepositoryCommitDiffResponse = GetRepositoryCommitDiffResponses[keyof GetRepositoryCommitDiffResponses];

export type GetRepositoryTreeData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Name
         */
        name: string;
        /**
         * Full tree sha
         */
        sha: string;
    };
    query?: never;
    url: '/repositories/{owner}/{name}/git/trees/{sha}';
};

export type GetRepositoryTreeErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type GetRepositoryTreeError = GetRepositoryTreeErrors[keyof GetRepositoryTreeErrors];

export type GetRepositoryTreeResponses = {
    /**
     * OK
     */
    200: GitTree;
};

export type GetRepositoryTreeResponse = GetRepositoryTreeResponses[keyof GetRepositoryTreeResponses];

export type ListReviewsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * At most this many (1-100)
         */
        limit?: number;
    };
    url: '/reviews';
};

export type ListReviewsErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
};

export type ListReviewsError = ListReviewsErrors[keyof ListReviewsErrors];

export type ListReviewsResponses = {
    /**
     * OK
     */
    200: ReviewList;
};

export type ListReviewsResponse = ListReviewsResponses[keyof ListReviewsResponses];

export type CreateReviewData = {
    /**
     * What to review
     */
    body: CreateReviewRequest;
    headers?: {
        /**
         * Makes retries safe
         */
        'Idempotency-Key'?: string;
    };
    path?: never;
    query?: never;
    url: '/reviews';
};

export type CreateReviewErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Too Many Requests
     */
    429: Problem;
};

export type CreateReviewError = CreateReviewErrors[keyof CreateReviewErrors];

export type CreateReviewResponses = {
    /**
     * Accepted
     */
    202: Review;
};

export type CreateReviewResponse = CreateReviewResponses[keyof CreateReviewResponses];

export type DeleteReviewData = {
    body?: never;
    path: {
        /**
         * Review ID
         */
        id: string;
    };
    query?: never;
    url: '/reviews/{id}';
};

export type DeleteReviewErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
};

export type DeleteReviewError = DeleteReviewErrors[keyof DeleteReviewErrors];

export type DeleteReviewResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteReviewResponse = DeleteReviewResponses[keyof DeleteReviewResponses];

export type GetReviewData = {
    body?: never;
    path: {
        /**
         * Review ID
         */
        id: string;
    };
    query?: never;
    url: '/reviews/{id}';
};

export type GetReviewErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
};

export type GetReviewError = GetReviewErrors[keyof GetReviewErrors];

export type GetReviewResponses = {
    /**
     * OK
     */
    200: Review;
};

export type GetReviewResponse = GetReviewResponses[keyof GetReviewResponses];

export type ListSessionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sessions';
};

export type ListSessionsErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
};

export type ListSessionsError = ListSessionsErrors[keyof ListSessionsErrors];

export type ListSessionsResponses = {
    /**
     * OK
     */
    200: SessionList;
};

export type ListSessionsResponse = ListSessionsResponses[keyof ListSessionsResponses];

export type DeleteCurrentSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sessions/current';
};

export type DeleteCurrentSessionErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
};

export type DeleteCurrentSessionError = DeleteCurrentSessionErrors[keyof DeleteCurrentSessionErrors];

export type DeleteCurrentSessionResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteCurrentSessionResponse = DeleteCurrentSessionResponses[keyof DeleteCurrentSessionResponses];

export type GetCurrentSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sessions/current';
};

export type GetCurrentSessionErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
};

export type GetCurrentSessionError = GetCurrentSessionErrors[keyof GetCurrentSessionErrors];

export type GetCurrentSessionResponses = {
    /**
     * OK
     */
    200: CurrentSession;
};

export type GetCurrentSessionResponse = GetCurrentSessionResponses[keyof GetCurrentSessionResponses];

export type DeleteSessionData = {
    body?: never;
    path: {
        /**
         * Session ID
         */
        id: string;
    };
    query?: never;
    url: '/sessions/{id}';
};

export type DeleteSessionErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
};

export type DeleteSessionError = DeleteSessionErrors[keyof DeleteSessionErrors];

export type DeleteSessionResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteSessionResponse = DeleteSessionResponses[keyof DeleteSessionResponses];

export type DeleteCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type DeleteCurrentUserErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
};

export type DeleteCurrentUserError = DeleteCurrentUserErrors[keyof DeleteCurrentUserErrors];

export type DeleteCurrentUserResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteCurrentUserResponse = DeleteCurrentUserResponses[keyof DeleteCurrentUserResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetCurrentUserErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
};

export type GetCurrentUserError = GetCurrentUserErrors[keyof GetCurrentUserErrors];

export type GetCurrentUserResponses = {
    /**
     * OK
     */
    200: User;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type UpdateCurrentUserData = {
    /**
     * New name
     */
    body: UpdateUserRequest;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UpdateCurrentUserErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
};

export type UpdateCurrentUserError = UpdateCurrentUserErrors[keyof UpdateCurrentUserErrors];

export type UpdateCurrentUserResponses = {
    /**
     * OK
     */
    200: User;
};

export type UpdateCurrentUserResponse = UpdateCurrentUserResponses[keyof UpdateCurrentUserResponses];
