// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (id, user_id, name, prefix, key_hash)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, prefix, key_hash, last_used_at, created_at
`

type CreateAPIKeyParams struct {
	ID      string
	UserID  string
	Name    string
	Prefix  string
	KeyHash []byte
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Prefix,
		arg.KeyHash,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (id, user_id, provider, provider_account_id, scopes,
                      access_token, access_expires_at, refresh_token, refresh_expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateAccountParams struct {
	ID                string
	UserID            string
	Provider          string
	ProviderAccountID string
	Scopes            []string
	AccessToken       []byte
	AccessExpiresAt   pgtype.Timestamptz
	RefreshToken      []byte
	RefreshExpiresAt  pgtype.Timestamptz
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.Exec(ctx, createAccount,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderAccountID,
		arg.Scopes,
		arg.AccessToken,
		arg.AccessExpiresAt,
		arg.RefreshToken,
		arg.RefreshExpiresAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, token_hash, expires_at, ip, user_agent)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateSessionParams struct {
	ID        string
	UserID    string
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	Ip        string
	UserAgent string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, name) VALUES ($1, $2, $3)
RETURNING id, email, name, created_at, updated_at
`

type CreateUserParams struct {
	ID    string
	Email string
	Name  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :execrows
DELETE FROM api_keys WHERE id = $1 AND user_id = $2
`

type DeleteAPIKeyParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAPIKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteSessionByID = `-- name: DeleteSessionByID :execrows
DELETE FROM sessions WHERE id = $1 AND user_id = $2
`

type DeleteSessionByIDParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteSessionByID(ctx context.Context, arg DeleteSessionByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionByID, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, user_id, name, prefix, key_hash, last_used_at, created_at FROM api_keys WHERE id = $1 AND user_id = $2
`

type GetAPIKeyParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetAPIKey(ctx context.Context, arg GetAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKey, arg.ID, arg.UserID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountGrant = `-- name: GetAccountGrant :one
SELECT provider_account_id, scopes, access_token, access_expires_at, refresh_token, refresh_expires_at
FROM accounts WHERE user_id = $1 AND provider = $2
FOR UPDATE
`

type GetAccountGrantParams struct {
	UserID   string
	Provider string
}

type GetAccountGrantRow struct {
	ProviderAccountID string
	Scopes            []string
	AccessToken       []byte
	AccessExpiresAt   pgtype.Timestamptz
	RefreshToken      []byte
	RefreshExpiresAt  pgtype.Timestamptz
}

func (q *Queries) GetAccountGrant(ctx context.Context, arg GetAccountGrantParams) (GetAccountGrantRow, error) {
	row := q.db.QueryRow(ctx, getAccountGrant, arg.UserID, arg.Provider)
	var i GetAccountGrantRow
	err := row.Scan(
		&i.ProviderAccountID,
		&i.Scopes,
		&i.AccessToken,
		&i.AccessExpiresAt,
		&i.RefreshToken,
		&i.RefreshExpiresAt,
	)
	return i, err
}

const getAccountUser = `-- name: GetAccountUser :one
SELECT u.id, u.email, u.name, u.created_at, u.updated_at
FROM accounts a JOIN users u ON u.id = a.user_id
WHERE a.provider = $1 AND a.provider_account_id = $2
`

type GetAccountUserParams struct {
	Provider          string
	ProviderAccountID string
}

type GetAccountUserRow struct {
	User User
}

func (q *Queries) GetAccountUser(ctx context.Context, arg GetAccountUserParams) (GetAccountUserRow, error) {
	row := q.db.QueryRow(ctx, getAccountUser, arg.Provider, arg.ProviderAccountID)
	var i GetAccountUserRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Email,
		&i.User.Name,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT u.id, u.email, u.name, u.created_at, u.updated_at, s.id AS session_id
FROM sessions s JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.expires_at > now()
`

type GetSessionUserRow struct {
	User      User
	SessionID string
}

func (q *Queries) GetSessionUser(ctx context.Context, tokenHash []byte) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i GetSessionUserRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Email,
		&i.User.Name,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.SessionID,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, name, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, created_at, updated_at FROM users WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, user_id, name, prefix, key_hash, last_used_at, created_at FROM api_keys WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeys(ctx context.Context, userID string) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Prefix,
			&i.KeyHash,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, user_id, token_hash, expires_at, ip, user_agent, created_at FROM sessions WHERE user_id = $1 AND expires_at > now() ORDER BY created_at DESC
`

func (q *Queries) ListSessions(ctx context.Context, userID string) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPIKey = `-- name: UpdateAPIKey :one
UPDATE api_keys SET name = $3 WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, prefix, key_hash, last_used_at, created_at
`

type UpdateAPIKeyParams struct {
	ID     string
	UserID string
	Name   string
}

func (q *Queries) UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, updateAPIKey, arg.ID, arg.UserID, arg.Name)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateAccountGrant = `-- name: UpdateAccountGrant :exec
UPDATE accounts
SET scopes = $3, access_token = $4, access_expires_at = $5, refresh_token = $6,
    refresh_expires_at = $7, updated_at = now()
WHERE provider = $1 AND provider_account_id = $2
`

type UpdateAccountGrantParams struct {
	Provider          string
	ProviderAccountID string
	Scopes            []string
	AccessToken       []byte
	AccessExpiresAt   pgtype.Timestamptz
	RefreshToken      []byte
	RefreshExpiresAt  pgtype.Timestamptz
}

func (q *Queries) UpdateAccountGrant(ctx context.Context, arg UpdateAccountGrantParams) error {
	_, err := q.db.Exec(ctx, updateAccountGrant,
		arg.Provider,
		arg.ProviderAccountID,
		arg.Scopes,
		arg.AccessToken,
		arg.AccessExpiresAt,
		arg.RefreshToken,
		arg.RefreshExpiresAt,
	)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET name = $2, updated_at = now() WHERE id = $1
RETURNING id, email, name, created_at, updated_at
`

type UpdateUserParams struct {
	ID   string
	Name string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const useAPIKey = `-- name: UseAPIKey :one
UPDATE api_keys k SET last_used_at = now()
WHERE k.key_hash = $1
RETURNING k.id, k.user_id
`

type UseAPIKeyRow struct {
	ID     string
	UserID string
}

func (q *Queries) UseAPIKey(ctx context.Context, keyHash []byte) (UseAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, useAPIKey, keyHash)
	var i UseAPIKeyRow
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}
