// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package sqlc

import (
	"context"
)

const claimReview = `-- name: ClaimReview :one
UPDATE reviews SET
    status = 'running',
    lease_owner = $1,
    lease_token = nextval('review_lease_token_seq'),
    lease_until = now() + make_interval(secs => $2::float8),
    attempts = attempts + 1,
    started_at = coalesce(started_at, now())
WHERE id = (
    SELECT id FROM reviews WHERE status = 'queued'
    ORDER BY created_at LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, user_id, source, note, status, result, reason, attempts, idempotency_key, request_hash, lease_owner, lease_token, lease_until, created_at, started_at, finished_at
`

type ClaimReviewParams struct {
	Owner      string
	TtlSeconds float64
}

func (q *Queries) ClaimReview(ctx context.Context, arg ClaimReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, claimReview, arg.Owner, arg.TtlSeconds)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Source,
		&i.Note,
		&i.Status,
		&i.Result,
		&i.Reason,
		&i.Attempts,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.LeaseOwner,
		&i.LeaseToken,
		&i.LeaseUntil,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const deleteReview = `-- name: DeleteReview :execrows
DELETE FROM reviews
WHERE id = $1 AND user_id = $2 AND status IN ('queued', 'done')
`

type DeleteReviewParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteReview(ctx context.Context, arg DeleteReviewParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReview, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishReview = `-- name: FinishReview :execrows
UPDATE reviews SET status = 'done', result = $1, reason = $2, finished_at = now(), lease_owner = ''
WHERE id = $3 AND lease_token = $4 AND status = 'running'
`

type FinishReviewParams struct {
	Result     string
	Reason     string
	ID         string
	LeaseToken int64
}

func (q *Queries) FinishReview(ctx context.Context, arg FinishReviewParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishReview,
		arg.Result,
		arg.Reason,
		arg.ID,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getReview = `-- name: GetReview :one
SELECT id, user_id, source, note, status, result, reason, attempts, idempotency_key, request_hash, lease_owner, lease_token, lease_until, created_at, started_at, finished_at FROM reviews WHERE id = $1 AND user_id = $2
`

type GetReviewParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetReview(ctx context.Context, arg GetReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, getReview, arg.ID, arg.UserID)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Source,
		&i.Note,
		&i.Status,
		&i.Result,
		&i.Reason,
		&i.Attempts,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.LeaseOwner,
		&i.LeaseToken,
		&i.LeaseUntil,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getReviewByIdempotencyKey = `-- name: GetReviewByIdempotencyKey :one
SELECT id, user_id, source, note, status, result, reason, attempts, idempotency_key, request_hash, lease_owner, lease_token, lease_until, created_at, started_at, finished_at FROM reviews WHERE user_id = $1 AND idempotency_key = $2
`

type GetReviewByIdempotencyKeyParams struct {
	UserID         string
	IdempotencyKey *string
}

func (q *Queries) GetReviewByIdempotencyKey(ctx context.Context, arg GetReviewByIdempotencyKeyParams) (Review, error) {
	row := q.db.QueryRow(ctx, getReviewByIdempotencyKey, arg.UserID, arg.IdempotencyKey)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Source,
		&i.Note,
		&i.Status,
		&i.Result,
		&i.Reason,
		&i.Attempts,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.LeaseOwner,
		&i.LeaseToken,
		&i.LeaseUntil,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertReview = `-- name: InsertReview :one
INSERT INTO reviews (id, user_id, source, note, status, idempotency_key, request_hash)
VALUES ($1, $2, $3, $4, 'queued', $5, $6)
ON CONFLICT (user_id, idempotency_key) DO NOTHING
RETURNING id, user_id, source, note, status, result, reason, attempts, idempotency_key, request_hash, lease_owner, lease_token, lease_until, created_at, started_at, finished_at
`

type InsertReviewParams struct {
	ID             string
	UserID         string
	Source         []byte
	Note           string
	IdempotencyKey *string
	RequestHash    []byte
}

func (q *Queries) InsertReview(ctx context.Context, arg InsertReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, insertReview,
		arg.ID,
		arg.UserID,
		arg.Source,
		arg.Note,
		arg.IdempotencyKey,
		arg.RequestHash,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Source,
		&i.Note,
		&i.Status,
		&i.Result,
		&i.Reason,
		&i.Attempts,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.LeaseOwner,
		&i.LeaseToken,
		&i.LeaseUntil,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listReviews = `-- name: ListReviews :many
SELECT id, user_id, source, note, status, result, reason, attempts, idempotency_key, request_hash, lease_owner, lease_token, lease_until, created_at, started_at, finished_at FROM reviews WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListReviewsParams struct {
	UserID string
	Limit  int32
}

func (q *Queries) ListReviews(ctx context.Context, arg ListReviewsParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, listReviews, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Source,
			&i.Note,
			&i.Status,
			&i.Result,
			&i.Reason,
			&i.Attempts,
			&i.IdempotencyKey,
			&i.RequestHash,
			&i.LeaseOwner,
			&i.LeaseToken,
			&i.LeaseUntil,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reapExpired = `-- name: ReapExpired :execrows
UPDATE reviews SET
    status = CASE WHEN attempts >= $1::int THEN 'done' ELSE 'queued' END,
    result = CASE WHEN attempts >= $1::int THEN 'none' ELSE result END,
    reason = CASE WHEN attempts >= $1::int THEN 'worker lost ' || attempts || ' times' ELSE reason END,
    finished_at = CASE WHEN attempts >= $1::int THEN now() ELSE finished_at END,
    lease_owner = ''
WHERE status = 'running' AND lease_until < now()
`

func (q *Queries) ReapExpired(ctx context.Context, maxAttempts int32) (int64, error) {
	result, err := q.db.Exec(ctx, reapExpired, maxAttempts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseReview = `-- name: ReleaseReview :execrows
UPDATE reviews SET status = 'queued', attempts = attempts - 1, lease_owner = ''
WHERE id = $1 AND lease_token = $2 AND status = 'running'
`

type ReleaseReviewParams struct {
	ID         string
	LeaseToken int64
}

func (q *Queries) ReleaseReview(ctx context.Context, arg ReleaseReviewParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseReview, arg.ID, arg.LeaseToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewLease = `-- name: RenewLease :execrows
UPDATE reviews SET lease_until = now() + make_interval(secs => $1::float8)
WHERE id = $2 AND lease_token = $3 AND status = 'running'
`

type RenewLeaseParams struct {
	TtlSeconds float64
	ID         string
	LeaseToken int64
}

func (q *Queries) RenewLease(ctx context.Context, arg RenewLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewLease, arg.TtlSeconds, arg.ID, arg.LeaseToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
